import "./globals.css";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  variable: "--roboto-default",
});

const roboto700 = Roboto({
  weight: "700",
  subsets: ["latin"],
  variable: "--roboto-bold",
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${roboto.className}
          ${roboto700.className}`}
      >
        {children}
      </body>
    </html>
  );
}
